version: '2'

services:
  backend:
    build: .
    image: fint/bluegarden-apapter-sse
    container_name: fint-bluegarden-apapter-sse
    restart: unless-stopped
    environment:
      PARAMS: ${runParams}
      TZ: Europe/Oslo
      logging.level.root: INFO
    ports:
      - "8097:8080"
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"