#!/bin/bash

echo ${DOCKER_CONTAINER}:${DOCKER_PORT}

# Build new image from compose
docker-compose build

# Stop service
docker-compose stop

# Remove container
docker-compose rm -f --all

# Start a new container with the built image
docker-compose up -d