#!/bin/bash

# Stop service
docker-compose stop

# Remove container
docker-compose rm -f --all

# Build new image from compose
docker-compose build

# Start a new container with the built image
docker-compose up -d